# Generated by Django 5.2.10 on 2026-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='alert_time',
        ),
        migrations.AddField(
            model_name='subscription',
            name='alert_interval_hours',
            field=models.IntegerField(default=24, help_text='Hours between alerts (e.g., 6, 12, 24)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
